MyFirstWithCMD/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/',views.about),
    path('',views.home),
    path('articles/',include('articles.urls')),
    path('accounts/',include('accounts.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup',views.signup_view, name = 'signup'),
    path('login',views.login_view, name='login'),
    path('logout',views.logout_view, name='logout'),
]

articles/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views


app_name='articles'
urlpatterns = [

    path('',views.articles_list, name="list"),
    path('create',views.create_article, name="create"),
    path('<slug>',views.article_detail,name="detail"),

]

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(default='default.jpg',blank=True)
    author = models.ForeignKey(User,default=None,on_delete=models.CASCADE)


    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[0:50]+' ...'

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title','slug','body','image']

MyFirstWithCMD/views.py
from django.shortcuts import render
from django.http import HttpResponse

def about(request):
    # return HttpResponse("Hello EveryOne")
    return render(request, 'about.html')
def home(response):
    # return HttpResponse('Welcome to my Home Page!')
    return render(request,'home.html')

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import authenticate,login,logout
# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()



    return render(request,'accounts/signup.html',{'form':form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

articles/views.py
from django.shortcuts import render, HttpResponse,redirect
from . import models
from django.contrib.auth.decorators import login_required
from . import forms
# Create your views here.
def articles_list(request):
    articles = models.Article.objects.all().order_by('date')
    args = {'articles': articles}
    return render(request,'articles/articleslist.html', args)

def article_detail(request,slug):
    # return HttpResponse(slug)
    article = models.Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html',{'article': article})

@login_required(login_url='/accounts/login')
def create_article(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            instanse = form.save(commit=False)
            instanse.author = request.user
            instanse.save()
            return redirect('articles:create')
    else:
        form = forms.CreateArticle()
    return render(request,'articles/create_article.html',{'form':form})

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{%  block content %}
    <form class="" action="{% url 'accounts:login' %}" method="post">
    {{ form }}
        {%  csrf_token %}
        {% if request.GET.next %}
        <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
    <input type="submit" value=" Login !">
    </form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{%  block content %}
    <form class="site-form" action="{%  url 'accounts:signup' %}" method="post">
    {{ form }}
        {%  csrf_token %}
    <input type="submit" value=" Submit !">
    </form>
{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base.html'%}

{% block content %}
<div class="article-detail">
    <div class="article">
        <img src="{{ article.image.url }}" , alt="">
        <h1>{{ article.title }}</h1>
        <p>{{ article.body }}</p>
        <p>{{ article.date }}</p>
    </div>
</div>
{% endblock %}

articles/templates/articles/articleslist.html
{% extends 'base.html' %}
{% block title %}articles{% endblock %}
{% block content %}
    <h1>articles</h1>
    {% for article in articles %}
        <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a> </h2>
        <p>{{ article.body }}</p>
        <p>{{ article.date }}</p>
        <p>{{ article.snippet }}</p>
    {% endfor %}
{% endblock %}

articles/templates/articles/create_article.html
{% extends 'base.html' %}
{% block title %}articles{% endblock %}
{% block content %}
<div>
    <h1>
        create your article
    </h1>
    <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
        {{ form }}
        {% csrf_token %}

        <input type="submit" name="" value="Create !">
    </form>
</div>

{% endblock %}

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title - Deleteed After After</title>
</head>
<body>
    <h1>about</h1>
    <p>Django</p>
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
        <title>
            {% block title %} Title {% endblock %}
        </title>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
<a href="{% url 'articles:list' %}">LOGO</a>
<nav>
    <ul>
        {% if user.is_authenticated %}
        <li>
            <form class="logout-link" action="{%  url "accounts:logout" %}" method="post">
                {%  csrf_token %}
                <button type="submit">logout</button>
            </form>
        </li>
        <li>
            <a href="{% url 'articles:create'%}">create new article</a>
        </li>
        {% else %}
        <li>
            <a href="{% url 'accounts:login' %}">login</a>
        </li>
            <li>
                <a href="{% url 'accounts:signup' %}">signup</a>
            </li>
        {% endif %}
    </ul>
</nav>
{% block content %}

{% endblock %}
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Home</h1>
    <p>Welcome to Django Home Page</p>
</body>
</html>